version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB
    ports:
      - "27017:27017"
    restart: always
  mongo-express:
    image: mongo-express
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=MongoDB
      - ME_CONFIG_MONGODB_URL=mongodb://root:MongoDB@mongo:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=mongo
      - ME_CONFIG_BASICAUTH_PASSWORD=mongo
    links:
      - mongo
    restart: unless-stopped
    ports:
      - "8081:8081"
